# Generated by Django 3.2.6 on 2021-08-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_text', models.CharField(help_text='Введите функцию. Например: t*t+/2.', max_length=100)),
                ('graph', models.ImageField(upload_to='')),
                ('dt', models.FloatField()),
                ('interval', models.FloatField()),
                ('date_modifed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
