# Generated by Django 3.2.6 on 2021-08-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graph',
            old_name='date_modifed',
            new_name='date_modified',
        ),
        migrations.AlterField(
            model_name='graph',
            name='function_text',
            field=models.CharField(help_text='Введите функцию. Например: t*t+t/2.', max_length=100),
        ),
        migrations.AlterField(
            model_name='graph',
            name='graph',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
