# Generated by Django 3.2 on 2021-08-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210814_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='graph',
            name='graph',
            field=models.ImageField(blank=True, upload_to='img/%Y%m%d/'),
        ),
    ]
