# Generated by Django 3.2 on 2021-08-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210817_1730'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Graph',
            new_name='MyGraph',
        ),
    ]
