# Generated by Django 3.2 on 2021-08-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210821_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygraph',
            name='graph',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
